select * from customer 
limit 10;


--Total revenue generated by Male and Female Customer.
select gender, sum(purchase_amount)
from customer 
group by gender;


-- Customer used a discount but still spent more than the average purchase amount. 
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

-- Top 5 products with the highest average review rating.
select item_purchased, round(avg(review_rating:: numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Campare the average Purchase Amounts betweern Standard and Express Shipping.
select shipping_type, round(avg(purchase_amount),2) as "Avg Purchase Amount"
from customer 
group by shipping_type
having shipping_type in ('Standard', 'Express')

--Do subcribed customers spend more ? Compare average spend and total revenue between Subcribers and non-subcribers.
select subscription_status, count(customer_id), round(avg(purchase_amount),2) as avg_spend, sum(purchase_amount) as total_revenue
from customer 
where subscription_status in ('Yes', 'No')
group by subscription_status
order by total_revenue, avg_spend desc;

-- 5 products have the highest percentage of purchases with discount applied.
select item_purchased, 
round(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/count(*),2) as discount_rate
from customer 
group by item_purchased
order by discount_rate desc
limit 5;

-- Segment customers into New, Returning, and Loyal based on their number of previous purchases,
--and  show the count of each segment.
with customer_type as(
select customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 then 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer
)

select customer_segment, count(*) as Number_of_Customers
from customer_type
group by customer_segment;

-- The top 3 most purchased products within each category.
with item_counts as (
select category, item_purchased, count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) item_rank
from customer 
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?
select  subscription_status, count(customer_id) as repeated_buyers
from customer
where previous_purchases > 5
group by subscription_status
order by count(customer_id) desc;

--Revenue contribution of each age group.
select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;







